name: CI 

on:
  push:
    branches: [Main]
    
jobs:
     CI:
       runs-on:  ubuntu-latest

       steps:

          - uses: actions/checkout@v4
        
          - name: Docker Login
            uses: docker/login-action@v3.3.0
            with:
              username: ${{  secrets.USER }}
              password: ${{  secrets.PASSWORD }}

          - name: Build and push Docker images
            uses: docker/build-push-action@v6.9.0
            with:
              context: .
              file: .
              push: true
              tags: | 
                heberton86/pipeline-docker-ci:v1
                heberton86/pipeline-docker-ci:latest
